global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
  external_labels:
    environment: production
    service: admirra

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 127.0.0.1:9090

  - job_name: nodes
    static_configs:
      - targets:
          - 10.77.0.1:9100
        labels:
          node: api1
          node_role: ingress-db-app
      - targets:
          - 10.77.0.2:9100
        labels:
          node: api2
          node_role: api-replica-redis

  - job_name: postgres
    static_configs:
      - targets:
          - 127.0.0.1:9187
        labels:
          node: api1
          node_role: database

  - job_name: redis
    static_configs:
      - targets:
          - 10.77.0.2:9121
        labels:
          node: api2
          redis_role: broker
      - targets:
          - 10.77.0.2:9122
        labels:
          node: api2
          redis_role: cache
