bind 0.0.0.0
protected-mode yes
port 6379
aclfile /etc/redis/users.acl
dir /data
appendonly yes
appendfsync everysec
save 900 1
maxmemory 256mb
maxmemory-policy noeviction
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
tcp-keepalive 60
loglevel notice
